name: Build and Upload to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker (optional, if your scripts use Docker)
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      # init submodules
      - name: Initialise Submodules
        uses: snickerbockers/submodules-init@v4

      # Install necessary packages (including 'repo' tool)
      - name: Install dependencies
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH 

      # Build docker image
      - name: Build Docker
        run: docker-compose build

      # Run the first script
      - name: Run setup-sources.sh
        run: |
          chmod +x ./scripts/setup-sources.sh
          ./scripts/setup-sources.sh

      # Run the second script
      - name: Run apply-patches.sh
        run: |
          chmod +x ./scripts/apply-patches.sh
          ./scripts/apply-patches.sh

      # Run the third script
      - name: Run build.sh
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      # Upload build output to GitHub Packages
      - name: Upload build output to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build-output
